consigne_4 <- div(id = "consigne_4",
                  br(),
                  fluidRow(column(6,
                                  h4("Pour finir cette expérience, nous vous demandons de répondre aux questions ci-dessous : "),
                                  offset = 3)),
                  #####################################################################################################
                  fluidRow(column(5,
                                  p("D'après vous quel est l'objectif de cette étude ?"),
                                  offset = 1),
                           column(4,
                                  textInput(inputId = "1_final",
                                            label = NULL),
                                  offset = 1)),
                  #====================================================================================================
                  fluidRow(column(5,
                                  p("Quelle a été votre stratégie pour la dernière tâche ?"),
                                  offset = 1),
                           column(4,
                                  textInput(inputId = "2_final",
                                            label = NULL),
                                  offset = 1)),
                  #====================================================================================================
                  fluidRow(column(5,
                                  p("Les choix que vous avez fait étaient-ils les mêmes que ceux que 
                                    vous aviez en tête en début de tâche ?"),
                                  offset = 1),
                           column(4,
                                  selectInput(inputId = "3_final",
                                              label = NULL,
                                              choices = c("Oui", "Non")),
                                  offset = 1)),
                  #====================================================================================================
                  fluidRow(column(5,
                                  p("Les taches de décompte étaient :"),
                                  offset = 1),
                           column(4,
                                  sliderInput(inputId = "4_final",
                                              label = "-5 = très pénible et 5 = très agréable",
                                              min = -5, max = 5,
                                              value = 0),
                                  offset = 1)),
                  #====================================================================================================
                  fluidRow(column(5,
                                  p("Pouvoir aller sur internet vous a t-il semblé être une activité attrayante ?"),
                                  offset = 1),
                           column(4,
                                  sliderInput(inputId = "5_final",
                                              label = "-5 = très pénible et 5 = très agréable",
                                              min = -5, max = 5,
                                              value = 0),
                                  offset = 1)),
                  #====================================================================================================
                  fluidRow(column(5,
                                  p("D'après vous combien de personnes dans la salle ont effectué des décompte pendant les 90 minutes ?"),
                                  offset = 1),
                           column(4,
                                  sliderInput(inputId = "6_final",
                                              label = "en % des personnes présentes",
                                              min = 0, max = 100,
                                              step = 5,
                                              value = 50),
                                  offset = 1)),
                  #====================================================================================================
                  fluidRow(column(5,
                                  p("Pour la seconde tâche, auriez vous agi différemment si vos décisions avaient été visibles ?"),
                                  offset = 1),
                           column(4,
                                  radioButtons(inputId = "7_final",
                                               label = NULL,
                                               choices = c("Oui", "Non")),
                                  offset = 1)),
                  #====================================================================================================
                  # fluidRow(column(5,
                  #                 p(""),
                  #                 offset = 1),
                  #          column(4,
                  #                 Input(inputId = "8_final"),
                  #                 offset = 1)),
                  #####################################################################################################
                  br(),
                  fluidRow(column(2, 
                                  actionButton(inputId = "rep_quest_fin",
                                               label = "Je valide mes réponses"),
                                  offset = 5))
                  # br(),
                  # br(),
                  # fluidRow(column(2, 
                  #                 hidden(div(id = "fin",
                  #                            actionButton(inputId = "rep_fin",
                  #                                         label = "J'ai fini !"),
                  #                            offset = 5))
                  # ))
)