consigne_2 <- div(id = "consigne_2",
                  br(),
                  br(),
                  fluidRow(column(8,
                                  includeMarkdown("texte/consigne_tache2.Rmd"),
                                  offset = 2)),
                  br(),
                  br(),
                  questionnaire("A", 
                                list("Si je choisis d'arrêter les décomptes au second écran de choix combien d'euros me rapportera cette tâche ?",
                                     "Si je paye pour ne plus voir l'écran de choix, combien de temps j'aurais passé au décompte à la fin de la tâche ?",
                                     "Si je continue normalement la tâche pendant 15 minutes, combien de fois maximum je verrais l'écran de choix pendant les 15 dernières minutes ?",
                                     "Si je choisis de payer pour ne plus voir les écrans de choix, à la fin de la tâche j'aurais gagné autant que si je continue normalement les décomptes pendant toute la tâche."), 
                                list(seq(0, 3, 0.5),
                                     seq(0, 30, 5),
                                     seq(0, 4, 1),
                                     c("Vrai", "Faux"))),
                  br(),
                  br(),
                  fluidRow(column(2, 
                                  hidden(div(id = "A_ok",
                                             actionButton("compris_2",
                                               "Je suis prêt!",
                                               onclick = "shinyjs.toggleFullScreen();"))),
                                  offset = 5)),
                  br(),
                  fluidRow(column(4,
                                  hidden(div(
                                    id = "cons_2_waiting",
                                    span("Merci d'attendre les autres participants", 
                                         style = "color:green")
                                  )),
                                  offset = 5))
)